title: ChenShang's Homepage
page-top-title: ChenShang
top-section-bg-text: Electronic Information Engineering
home-subtitle: ChenShang&ensp;|&ensp;晨殇
copyright-text: '&copy; ChenShang 2023-2025. All Rights Reserved.'
